### ISSUE TITLE
'RNShadowTextGradient.h' file not found

### ISSUE THREAD

**Issue by FransTwisk** [iyegoroff/react-native-text-gradient#1]
Don't see this file in the repo either...

```▸ Compiling RNShadowRadialTextGradient.m

❌  .../ios/Pods/ReactNativeTextGradient/ios/RNShadowRadialTextGradient.h:1:9: 'RNShadowTextGradient.h' file not found

#import "RNShadowTextGradient.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~```

**Comment by iyegoroff** [comment]
Removed references to radial gradient sources in 0.0.6

**Comment by FransTwisk** [comment]
I'm using cocoapods to load the libraries and it still crashes because the actual file tries to import a library that's not there.

**Comment by FransTwisk** [comment]
Just dropping this here since this is still open: version 0.0.8 still has version 0.0.7 in package.json so I can't install it correctly.

**Comment by johhansantana** [comment]
I'm still getting this issue. I installed library using yarn and link them using `react-native link`.

```
/react-native/Libraries/Text/BaseText/RCTBaseTextShadowView.h:8:9: 'React/RCTShadowView.h' file not found
```

I'm not sure what do you mean by deleting all obj-c files. What's the process on doing this correctly?

**Comment by iyegoroff** [comment]
@johhansantana, there was a lot of changes since this issue was closed - if you have a problem with rntg, consider creating new issue and follow provided issue template.
