### ISSUE TITLE
Update compiledSdkVersion to 25

### ISSUE THREAD

**Issue by MrCreeper1008** [iyegoroff/react-native-text-gradient#12]
- **Platform**: Android
- **React Native version**: 0.56  
- **React Native Text Gradient version**: 0.0.8  

React Native 0.56 requires sdk version to be at least 25.0 but react-native-text-gradient still uses 23.0.  

Error output:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-text-gradient'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-text-gradient'. Minimum required is 25.0.0
```

**Comment by iyegoroff** [comment]
rntg 0.0.8 is not compatible with rn 0.56, you need to upgrade 
https://github.com/iyegoroff/react-native-text-gradient#status

**Comment by MrCreeper1008** [comment]
yea sorry i thought i was on the latest version
