### ISSUE TITLE
Build Failed in iOS

### ISSUE THREAD

**Issue by Balasnest** [iyegoroff/react-native-text-gradient#19]
Getting build failed in iOS only

`React/RCTShadowView.h file not found`

Done `npm link` also. what would be the problem?

react-native: 0.51.0
react-native-text-gradient: 0.0.3

Using the right target version:
**with rn >= 0.50.0 use 0.0.3.**

**Comment by Balasnest** [comment]
![simulator screen shot - iphone x - 2018-11-08 at 12 49 11](https://user-images.githubusercontent.com/6050520/48183491-d8de3780-e354-11e8-9620-57fb48a8eb2d.png)

**Comment by iyegoroff** [comment]
Just checked rn 0.51.0 + rntg 0.0.3 on iOS - it compiles and runs without errors. Probably you didn't link the module properly or using a newer rntg version.
