### ISSUE TITLE
No visible @interface for 'RCTBaseTextShadowView<RNTextGradientShadowViewDelegate>' declares the selector 'frame'

### ISSUE THREAD

**Issue by ethanyuwang** [iyegoroff/react-native-text-gradient#2]
I had this error when I tried to compile the ios app:

/Users/.../node_modules/react-native-text-gradient/ios/RNTextGradientShadowView.m:94:46: No visible @interface for 'RCTBaseTextShadowView<RNTextGradientShadowViewDelegate>' declares the selector 'frame'

**Comment by iyegoroff** [comment]
What `react-native` and `react-native-text-gradient` versions do you use?

**Comment by iyegoroff** [comment]
Fixed in 0.0.8

**Comment by FransTwisk** [comment]
Just dropping this here since it was about the same issue: version 0.0.8 still has version 0.0.7 in package.json so I can't install it correctly.
