### ISSUE TITLE
App got crashed after creating offline bundle in both IOS and Android

### ISSUE THREAD

**Issue by saikiranoptisol** [iyegoroff/react-native-text-gradient#20]
during development if i run the code the gradient for text is working fine. But if i create any offline bundle ie: .ipa or .apk file and install it in corresponding devices the app got crashed and cant able to solve issue from few days. without react-native-text-gradient everything works fine.

**Comment by iyegoroff** [comment]
If your app crashed due to react-native-text-gradient, please attach a crash log.

**Comment by saikiranoptisol** [comment]
> If your app crashed due to react-native-text-gradient, please attach a crash log.

how to get that crash log? i'm new to reactnative and i dont know how to do it

**Comment by saikiranoptisol** [comment]
hi, it is showing the Text strings must be rendered with in a <Text> component, for this in previous issues it is shown to use node node_modules/react-native-text-gradient/patch-rn.js.  if i was in development mode i can use terminal and follow that but once i created a .apk file and .ipa file how i can get rid of this issue.

**Comment by iyegoroff** [comment]
I'm closing this issue because can't do anything here without a crash log. Feel free to reopen it again when you have a crash log.

**Comment by saikiranoptisol** [comment]
how you can close this issue even though there is no crashlog for my project, in ios its directly crashing without showing any error, but in android it is Showing  text strings must be rendered within a <Text> component. for this there is a patch that need to done in terminal. But after creating offline bundle and .apk and .ipa files how can i use terminal. kindly understand the  issue and reopen it.


Steps to reproduce:
1.create sample project with react-native-text-gradient 
2. while running in xcode or android emulator you will get issue text strings must be rendered within a <Text> component. to avodi this add $ node node_modules/react-native-text-gradient/patch-rn.js in terminal.
3. now create .apk file for android and .ipa file in IOS. install it in corresponding devices.
4.IOS App crashes, Android app crashes and shows  text strings must be rendered within a <Text> component.

how to get rid of this issue? Reopen the issue again

**Comment by yungobiwan** [comment]
I get the same error in iOS as well.

**Comment by saikiranoptisol** [comment]
@iyegoroff   Kindly Reopen the issue and provide solution for this

**Comment by saikiranoptisol** [comment]
Anyway I have done may searches why its happening for me. I cant find any issues previously like that. So after many searches now I'm finally react-native-svg which is working fine for me....

**Comment by fukemy** [comment]
really shit
