### ISSUE TITLE
element type is invalid

### ISSUE THREAD

**Issue by codex7** [iyegoroff/react-native-text-gradient#21]
i get this error:
Element type is invalid: expected a string or a class/function(for composite components) but got: object

I changed the import, but did not work:
import LinearTextGradient  from 'react-native-text-gradient';

please help

**Comment by iyegoroff** [comment]
https://github.com/iyegoroff/react-native-text-gradient#example

**Comment by codex7** [comment]
I used the following code:
import { LinearTextGradient } from 'react-native-text-gradient';

<LinearTextGradient
  style={{ fontWeight: 'bold', fontSize: 72 }}
  locations={[0, 1]}
  colors={['red', 'blue']}
  start={{ x: 0, y: 0 }}
  end={{ x: 1, y: 0 }}
>
  THIS IS TEXT GRADIENT
</LinearTextGradient>
The problem did not resolve

**Comment by iyegoroff** [comment]
Looks like you forgot the closing tag.

**Comment by codex7** [comment]
I forgot to use the tag code in the github:

mycode:

```
<LinearTextGradient
  style={{ fontWeight: 'bold', fontSize: 72 }}
  locations={[0, 1]}
  colors={['red', 'blue']}
  start={{ x: 0, y: 0 }}
  end={{ x: 1, y: 0 }}
>
  THIS IS TEXT GRADIENT
</LinearTextGradient>
```

rn version: 0.54

**Comment by iyegoroff** [comment]
And what is your rntg version? Should be 0.0.7 - https://github.com/iyegoroff/react-native-text-gradient#status

**Comment by codex7** [comment]
Thanks
Because it was written with        **rn>** = 0.54.0 use 0.0.7       i used the latest version
