### ISSUE TITLE
react-native-text-gradient not working for RN  version 0.57.4 Error

### ISSUE THREAD

**Issue by sunithakk** [iyegoroff/react-native-text-gradient#22]
for RN version 0.55.2 getting  below Error.
: Unable to resolve module `react-native/Libraries/Text/TextAncestor` from `C:\Users\CR-27\creatise\claptest\node_modules\react-native-text-gradient\src\create-text-gradient-class.js`: Module `react-native/Libraries/Text/TextAncestor` does not exist in the Haste module map

**Comment by iyegoroff** [comment]
Didn't get what is your rn version, please specify it and select corresponding rntg version from here - https://github.com/iyegoroff/react-native-text-gradient#status

**Comment by sunithakk** [comment]
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "native-base": "^2.8.1",
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.4",
    "react-native-device-info": "^0.24.3",
    "react-native-elements": "^1.0.0-beta7",
    "react-native-fbsdk": "^0.8.0",
    "react-native-splash-screen": "^3.1.1",
    "react-native-text-gradient": "0.0.16",
    "react-native-vector-icons": "^6.1.0",
    "react-navigation": "^2.18.2",
    "tcomb-form-native": "^0.6.20"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.0",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by iyegoroff** [comment]
Probably this is a build issue and is not related to rntg. Can you try to check if this error replicates on a fresh project?
