### ISSUE TITLE
cocoapods build failure

### ISSUE THREAD

**Issue by jakobereksen** [iyegoroff/react-native-text-gradient#27]
react-native version: 0.59
react-native-text-gradient version: 0.1.4

Using cocoapods for all iOS dependencies with use_frameworks!

iOS build fails with
`Undefined symbols for architecture x86_64:
  "_OBJC_IVAR_$_RCTTextShadowView._bridge", referenced from:
      -[RNTextGradientShadowView uiManagerWillPerformMounting] in RNTextGradientView(RNTextGradientShadowView.o)
  "_OBJC_IVAR_$_RCTTextView._textStorage", referenced from:
      -[RNTextGradientView drawRect:] in RNTextGradientView(RNTextGradientView.o)
  "_OBJC_IVAR_$_RCTTextViewManager._shadowViews", referenced from:
      -[RNTextGradientViewManager shadowView] in RNTextGradientView(RNTextGradientViewManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by iyegoroff** [comment]
@jakobereksen, I never used rntg this way, so I'm not sure how to resolve your issue. Cocoapods integration was implemented by @rowinbot. If there are cocoapods related erros and you know how to fix them - please submit a PR.

**Comment by jakobereksen** [comment]
i tried a few things, but did not have success. @rowinbot do you have an idea?

**Comment by iyegoroff** [comment]
It appears that .podspec file was missing from "files" field in package.json before v0.1.6. 
I'm going to close this issue for now, but feel free to reopen it again if you still experiencing this error with rntg >= 0.1.6

**Comment by JayantJoseph** [comment]
> @jakobereksen I meet this issue and fix it with a trick way. Delete these lines and use KVC to get the instance variable.
> ![1](https://user-images.githubusercontent.com/12869456/57375235-7a90f500-71cf-11e9-942f-050402783e25.png)

Please Help how to use KVC to get the instance variable?
In 0.1.7 and still have this problem!!

**Comment by Nemocdz** [comment]
RCTBridge *bridge = [self valueForKey:@"_bridge"];
