### ISSUE TITLE
RNTextGradient/RNShadowTextGradient.java:209: error: cannot  find symbol that.mJustificationMode

### ISSUE THREAD

**Issue by squid17** [iyegoroff/react-native-text-gradient#29]
RNTextGradient/RNShadowTextGradient.java:209: error: cannot
 find symbol
              that.mJustificationMode
                  ^
  symbol:   variable mJustificationMode
  location: variable that of type RNShadowTextGradient

react-native:0.57.8
react-native-text-gradient: 0.1.6

**Comment by iyegoroff** [comment]
Looks like mJustificationMode was added in v0.59.0 - https://github.com/facebook/react-native/commit/8d95e734bb318e245ceb39a85e703403a47fba52#diff-b9097bc72809ab84057ff8a0b1e0cce0R268.

So with rn v0.57.8 you have to use rntg v0.0.17
