### ISSUE TITLE
'RCTTextShadowView.h' file not found

### ISSUE THREAD

**Issue by juand89** [iyegoroff/react-native-text-gradient#4]
My build failed with this message, and the simulator shows:
No component found for view with name "RNLinearTextGradient"
Using the latest version 0.0.8

**Comment by iyegoroff** [comment]
Most likely you forgot to link the module or using it with wrong react-native version:
https://github.com/iyegoroff/react-native-text-gradient#mostly-automatic-installation
https://github.com/iyegoroff/react-native-text-gradient#status

**Comment by juand89** [comment]
Thank you, I was using the wrong version. I downgrade to the version 0.0.3 because I am using the .52 version of RN and now I dont have any problems.

**Comment by Balasnest** [comment]
@iyegoroff  May I know what would be the problem?
