### ISSUE TITLE
No ViewManager defined for class RNLinearTextGradient

### ISSUE THREAD

**Issue by Noor0** [iyegoroff/react-native-text-gradient#5]
i am getting this error 
here are my dependencies and their versions 
"dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-elements": "^0.19.1",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-text-gradient": "^0.0.8",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.3.1"
  },

**Comment by iyegoroff** [comment]
I think you didn't link the module - https://github.com/iyegoroff/react-native-text-gradient#mostly-automatic-installation

**Comment by Noor0** [comment]
i tried linking the module both manually and automatically but nothing worked

**Comment by iyegoroff** [comment]
You can clone this repo and check if you still receive this error on example project - https://github.com/iyegoroff/react-native-text-gradient/tree/master/TextGradientExample
